100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow and in the numpy documentation. The goal of this collection is to offer a quick reference for both old and new users but also to provide a set of exercises for those who teach.

In [4]:
import numpy as np 

In [5]:
# 2. Print the numpy version and the configuration
print("NumPy Version:", np.__version__)
print("NumPy Configuration:\n", np.show_config())

NumPy Version: 1.26.2
{
  "Compilers": {
    "c": {
      "name": "msvc",
      "linker": "link",
      "version": "19.29.30152",
      "commands": "cl"
    },
    "cython": {
      "name": "cython",
      "linker": "cython",
      "version": "3.0.5",
      "commands": "cython"
    },
    "c++": {
      "name": "msvc",
      "linker": "link",
      "version": "19.29.30152",
      "commands": "cl"
    }
  },
  "Machine Information": {
    "host": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    },
    "build": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    }
  },
  "Build Dependencies": {
    "blas": {
      "name": "openblas64",
      "found": true,
      "version": "0.3.23.dev",
      "detection method": "pkgconfig",
      "include directory": "/c/opt/64/include",
      "lib directory": "/c/opt/64/lib",
      "openblas configuration": "USE_64BITINT=1 DYNAMIC_ARCH=1 DYN

c:\Users\Aisha\AppData\Local\Programs\Python\Python312\Lib\site-packages\numpy\__config__.py:149: UserWarning: Install `pyyaml` for better output
  warnings.warn("Install `pyyaml` for better output", stacklevel=1)


In [6]:
# 3. Create a null vector of size 10
null_vector = np.zeros(10)
print("Null Vector:", null_vector)

Null Vector: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [7]:
# 4. How to find the memory size of any array
array = np.array([1, 2, 3])
print("Memory size of the array:", array.nbytes, "bytes")

Memory size of the array: 12 bytes


In [ ]:
# 5. How to get the documentation of the numpy add function from the command line?
# (Use the following command in the command line)
# python -c "import numpy; numpy.info(numpy.add)"

In [8]:
# 6. Create a null vector of size 10 but the fifth value which is 1
null_vector_with_one = np.zeros(10)
null_vector_with_one[4] = 1
print("Null Vector with 1 at the fifth position:", null_vector_with_one)


Null Vector with 1 at the fifth position: [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [9]:
# 7. Create a vector with values ranging from 10 to 49
vector_10_to_49 = np.arange(10, 50)
print("Vector from 10 to 49:", vector_10_to_49)


Vector from 10 to 49: [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [10]:
# 8. Reverse a vector (first element becomes last)
reversed_vector = np.flip(vector_10_to_49)
print("Reversed Vector:", reversed_vector)

Reversed Vector: [49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [11]:
# 9. Create a 3x3 matrix with values ranging from 0 to 8
matrix_3x3 = np.arange(9).reshape(3, 3)
print("3x3 Matrix:", matrix_3x3)

3x3 Matrix: [[0 1 2]
 [3 4 5]
 [6 7 8]]


In [12]:
# 10. Find indices of non-zero elements from [1,2,0,0,4,0]
non_zero_indices = np.nonzero([1, 2, 0, 0, 4, 0])
print("Indices of non-zero elements:", non_zero_indices)

Indices of non-zero elements: (array([0, 1, 4], dtype=int64),)


In [13]:
# 11. Create a 3x3 identity matrix
identity_matrix = np.identity(3)
print("3x3 Identity Matrix:\n", identity_matrix)

3x3 Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [14]:
# 12. Create a 3x3x3 array with random values
random_3x3x3_array = np.random.random((3, 3, 3))
print("3x3x3 Array with Random Values:\n", random_3x3x3_array)


3x3x3 Array with Random Values:
 [[[0.9627567  0.26922951 0.64435666]
  [0.54972497 0.31710736 0.50989371]
  [0.69751041 0.08215634 0.00506847]]

 [[0.04405567 0.67938582 0.1079492 ]
  [0.19296504 0.18174021 0.18988143]
  [0.7234778  0.40533584 0.51456515]]

 [[0.13470829 0.41146606 0.29612067]
  [0.54337059 0.99524629 0.69842481]
  [0.14992845 0.44743807 0.24986342]]]


In [15]:
# 13. Create a 10x10 array with random values and find the minimum and maximum values
random_10x10_array = np.random.random((10, 10))
min_value = np.min(random_10x10_array)
max_value = np.max(random_10x10_array)
print("Minimum Value:", min_value)
print("Maximum Value:", max_value)

Minimum Value: 0.0007596001448221257
Maximum Value: 0.9815565453109979


In [17]:
# 13. Create a 10x10 array with random values and find the minimum and maximum values
random_10x10_array = np.random.random((10, 10))
min_value = np.min(random_10x10_array)
max_value = np.max(random_10x10_array)
print("Minimum Value:", min_value)
print("Maximum Value:", max_value)

Minimum Value: 0.016349373224420982
Maximum Value: 0.99035566952107


In [18]:
# 15. Create a 2d array with 1 on the border and 0 inside
border_array = np.ones((5, 5))
border_array[1:-1, 1:-1] = 0
print("2D Array with Border of 1 and Inside 0:\n", border_array)


2D Array with Border of 1 and Inside 0:
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [19]:
# 15. Create a 2d array with 1 on the border and 0 inside
border_array = np.ones((5, 5))
border_array[1:-1, 1:-1] = 0
print("2D Array with Border of 1 and Inside 0:\n", border_array)


2D Array with Border of 1 and Inside 0:
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [20]:
# 17. What is the result of the following expression?
# (printing each part)
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


In [22]:
# 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal
diagonal_below_matrix = np.diag(1 + np.arange(4), k=-1)
print("5x5 Matrix with Values 1,2,3,4 Below the Diagonal:\n", diagonal_below_matrix)


5x5 Matrix with Values 1,2,3,4 Below the Diagonal:
 [[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [23]:
# 19. Create a 8x8 matrix and fill it with a checkerboard pattern
checkerboard_matrix = np.zeros((8, 8), dtype=int)
checkerboard_matrix[1::2, ::2] = 1
checkerboard_matrix[::2, 1::2] = 1
print("Checkerboard Pattern 8x8 Matrix:\n", checkerboard_matrix)


Checkerboard Pattern 8x8 Matrix:
 [[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [24]:
# 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?
array_shape = (6, 7, 8)
index_100th_element = np.unravel_index(100, array_shape)
print("Index of the 100th Element:", index_100th_element)


Index of the 100th Element: (1, 5, 4)


In [26]:
# 21. Create a checkerboard 8x8 matrix using the tile function
checkerboard_tile = np.tile(np.array([[0, 1], [1, 0]]), (4, 4))
print("Checkerboard Pattern 8x8 Matrix using Tile:\n", checkerboard_tile)


Checkerboard Pattern 8x8 Matrix using Tile:
 [[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [27]:
# 22. Normalize a 5x5 random matrix
random_5x5_matrix = np.random.random((5, 5))
normalized_matrix = (random_5x5_matrix - np.mean(random_5x5_matrix)) / np.std(random_5x5_matrix)
print("Normalized 5x5 Matrix:\n", normalized_matrix)

Normalized 5x5 Matrix:
 [[ 0.77000161 -0.72167136 -0.23688686  0.05087741 -0.84309808]
 [-0.24684307 -1.24943627  1.60638972 -1.26890578 -1.0771756 ]
 [ 1.1187592   0.10934539  0.89759658 -0.85235597 -1.5951733 ]
 [ 1.26146914  0.32315893  1.52539506 -1.37473681 -0.43914983]
 [ 0.31886852  0.45737376  1.19269834  1.34657713 -1.07307788]]


In [28]:
# 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA)
color_dtype = np.dtype([('R', 'u1'), ('G', 'u1'), ('B', 'u1'), ('A', 'u1')])
print("Custom Color dtype:", color_dtype)

Custom Color dtype: [('R', 'u1'), ('G', 'u1'), ('B', 'u1'), ('A', 'u1')]


In [29]:
# 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)
matrix_5x3 = np.random.random((5, 3))
matrix_3x2 = np.random.random((3, 2))
product_matrix = np.dot(matrix_5x3, matrix_3x2)
print("Matrix Product of 5x3 and 3x2 matrices:\n", product_matrix)


Matrix Product of 5x3 and 3x2 matrices:
 [[0.65512326 0.5379972 ]
 [0.75542618 0.6629485 ]
 [1.16818761 0.91958568]
 [1.2472182  1.15805862]
 [0.65098025 0.64061616]]


In [30]:
# 25. Given a 1D array, negate all elements which are between 3 and 8, in place
array_1d = np.arange(10)
array_1d[(array_1d > 3) & (array_1d < 8)] *= -1
print("Negated elements between 3 and 8:", array_1d)

Negated elements between 3 and 8: [ 0  1  2  3 -4 -5 -6 -7  8  9]


In [31]:
# 26. What is the output of the following script?
# Author: Jake VanderPlas
print(sum(range(5), -1))
from numpy import *
print(sum(range(5), -1))

9
10


In [33]:
# 27. Consider an integer vector Z, which of these expressions are legal?
# (Testing each expression individually)
Z = np.array([1, 2, 3])
print(Z**Z)
print(2 << Z >> 2)
print(Z < -Z)
print(1j * Z)
print(Z / 1 / 1)
# print(Z < Z > Z) (value error)


[ 1  4 27]
[1 2 4]
[False False False]
[0.+1.j 0.+2.j 0.+3.j]
[1. 2. 3.]


In [34]:
# 28. What are the result of the following expressions?
print(np.array(0) / np.array(0))     
print(np.array(0) // np.array(0))    
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-2.14748365e+09]


C:\Users\Aisha\AppData\Local\Temp\ipykernel_11704\892098047.py:2: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))     # nan
C:\Users\Aisha\AppData\Local\Temp\ipykernel_11704\892098047.py:3: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))    # 0
C:\Users\Aisha\AppData\Local\Temp\ipykernel_11704\892098047.py:4: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))


In [35]:
# 29. How to round away from zero a float array?
float_array = np.random.uniform(-10, 10, 5)
rounded_array = np.copysign(np.ceil(np.abs(float_array)), float_array)
print("Original Float Array:", float_array)
print("Rounded Away from Zero Array:", rounded_array)

Original Float Array: [-8.60521523 -8.94431087 -2.03675727 -0.50976483 -0.33751221]
Rounded Away from Zero Array: [-9. -9. -3. -1. -1.]


In [36]:
# 30. How to find common values between two arrays?
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([3, 4, 5, 6, 7])
common_values = np.intersect1d(array1, array2)
print("Common values between two arrays:", common_values)

Common values between two arrays: [3 4 5]


In [37]:
# 31. How to ignore all numpy warnings (not recommended)?
# (Not recommended, but here is the code)
np.seterr(all='ignore')

{'divide': 'warn', 'over': 'warn', 'under': 'ignore', 'invalid': 'warn'}

In [38]:
# 32. Is the following expressions true?
print(np.sqrt(-1) == np.emath.sqrt(-1)) 

False


In [39]:
# 33. How to get the dates of yesterday, today and tomorrow?
yesterday = np.datetime64('today') - np.timedelta64(1, 'D')
today = np.datetime64('today')
tomorrow = np.datetime64('today') + np.timedelta64(1, 'D')
print("Yesterday:", yesterday)
print("Today:", today)
print("Tomorrow:", tomorrow)

Yesterday: 2024-02-05
Today: 2024-02-06
Tomorrow: 2024-02-07


In [40]:
# 34. How to get all the dates corresponding to the month of July 2016?
dates_july_2016 = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print("Dates in July 2016:", dates_july_2016)

Dates in July 2016: ['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


In [41]:
# 35. How to compute ((A+B)*(-A/2)) in place (without copy)?
A = np.ones(3)
B = np.ones(3) * 2
np.multiply(np.add(A, B, out=B), np.negative(A, out=A), out=B)
print("Result of ((A+B)*(-A/2)):", B)

Result of ((A+B)*(-A/2)): [-3. -3. -3.]


In [42]:
# 36. Extract the integer part of a random array of positive numbers using 4 different methods
random_positive_array = np.random.uniform(0, 10, 5)
integer_part_method1 = random_positive_array.astype(int)
integer_part_method2 = np.floor(random_positive_array)
integer_part_method3 = np.ceil(random_positive_array) - 1
integer_part_method4 = np.trunc(random_positive_array)
print("Original Random Positive Array:", random_positive_array)
print("Integer Part (Method 1):", integer_part_method1)
print("Integer Part (Method 2):", integer_part_method2)
print("Integer Part (Method 3):", integer_part_method3)
print("Integer Part (Method 4):", integer_part_method4)

Original Random Positive Array: [3.90508955 1.0559698  9.69936865 3.1873246  6.02786303]
Integer Part (Method 1): [3 1 9 3 6]
Integer Part (Method 2): [3. 1. 9. 3. 6.]
Integer Part (Method 3): [3. 1. 9. 3. 6.]
Integer Part (Method 4): [3. 1. 9. 3. 6.]


In [43]:
# 37. Create a 5x5 matrix with row values ranging from 0 to 4
matrix_row_values = np.zeros((5, 5))
matrix_row_values += np.arange(5)
print("5x5 Matrix with Row Values 0 to 4:\n", matrix_row_values)


5x5 Matrix with Row Values 0 to 4:
 [[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [44]:
# 38. Consider a generator function that generates 10 integers and use it to build an array
generator_function = (x for x in range(10))
array_from_generator = np.fromiter(generator_function, int)
print("Array built from Generator Function:", array_from_generator)


Array built from Generator Function: [0 1 2 3 4 5 6 7 8 9]


In [45]:
# 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded
vector_excluded_values = np.linspace(0, 1, 12)[1:-1]
print("Vector with Values Ranging from 0 to 1 (Excluded):\n", vector_excluded_values)


Vector with Values Ranging from 0 to 1 (Excluded):
 [0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [46]:
# 40. Create a random vector of size 10 and sort it
random_vector_10 = np.random.random(10)
sorted_vector = np.sort(random_vector_10)
print("Random Vector of Size 10:", random_vector_10)
print("Sorted Vector:", sorted_vector)

Random Vector of Size 10: [0.46806143 0.34023939 0.54966482 0.10395876 0.64253357 0.72495028
 0.81038486 0.30499189 0.42482348 0.01755417]
Sorted Vector: [0.01755417 0.10395876 0.30499189 0.34023939 0.42482348 0.46806143
 0.54966482 0.64253357 0.72495028 0.81038486]


In [47]:
# 41. How to sum a small array faster than np.sum?
small_array = np.arange(10)
sum_faster = np.add.reduce(small_array)
print("Sum of Small Array Faster than np.sum:", sum_faster)


Sum of Small Array Faster than np.sum: 45


In [48]:
# 42. Consider two random array A and B, check if they are equal
array_A = np.random.random(5)
array_B = np.random.random(5)
are_equal = np.array_equal(array_A, array_B)
print("Arrays A and B are equal:", are_equal)

Arrays A and B are equal: False


In [49]:
# 43. Make an array immutable (read-only)
immutable_array = np.zeros(5)
immutable_array.flags.writeable = False
# Attempting to modify the array will raise an error
# immutable_array[0] = 1

In [50]:
# 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates
cartesian_coordinates = np.random.random((10, 2))
x, y = cartesian_coordinates[:, 0], cartesian_coordinates[:, 1]
r = np.sqrt(x**2 + y**2)
theta = np.arctan2(y, x)
polar_coordinates = np.column_stack((r, theta))
print("Random Cartesian Coordinates:\n", cartesian_coordinates)
print("Converted Polar Coordinates:\n", polar_coordinates)

Random Cartesian Coordinates:
 [[0.36535742 0.99735419]
 [0.97170005 0.18953232]
 [0.4414444  0.31640763]
 [0.00613981 0.84452102]
 [0.41880228 0.03853466]
 [0.17872994 0.15141295]
 [0.55381828 0.21745543]
 [0.06014491 0.04636455]
 [0.5452553  0.99297347]
 [0.52136592 0.66889212]]
Converted Polar Coordinates:
 [[1.06216826 1.21965129]
 [0.99001186 0.19263365]
 [0.54312701 0.62188287]
 [0.84454334 1.56352629]
 [0.42057136 0.09175324]
 [0.23424405 0.70284328]
 [0.59498029 0.37415209]
 [0.0759413  0.65673141]
 [1.13282816 1.06863386]
 [0.84807965 0.90871398]]


In [51]:
# 45. Create random vector of size 10 and replace the maximum value by 0
random_vector_replace_max = np.random.random(10)
random_vector_replace_max[random_vector_replace_max.argmax()] = 0
print("Random Vector with Maximum Value Replaced by 0:", random_vector_replace_max)


Random Vector with Maximum Value Replaced by 0: [0.69589526 0.62804941 0.         0.10060474 0.24537696 0.61622647
 0.06127095 0.23833633 0.97691528 0.98670777]


In [52]:
# 46. Create a structured array with x and y coordinates covering the [0,1]x[0,1] area
structured_array = np.zeros((5, 5), [('x', float), ('y', float)])
structured_array['x'], structured_array['y'] = np.meshgrid(np.linspace(0, 1, 5), np.linspace(0, 1, 5))
print("Structured Array with x and y Coordinates:\n", structured_array)


Structured Array with x and y Coordinates:
 [[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


In [53]:
# 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij = 1/(xi - yj))
X = np.arange(1, 6)
Y = X + 0.5
Cauchy_matrix = 1.0 / np.subtract.outer(X, Y)
print("Cauchy Matrix C:\n", Cauchy_matrix)

Cauchy Matrix C:
 [[-2.         -0.66666667 -0.4        -0.28571429 -0.22222222]
 [ 2.         -2.         -0.66666667 -0.4        -0.28571429]
 [ 0.66666667  2.         -2.         -0.66666667 -0.4       ]
 [ 0.4         0.66666667  2.         -2.         -0.66666667]
 [ 0.28571429  0.4         0.66666667  2.         -2.        ]]


In [55]:
# 48. Print the minimum and maximum representable value for each numpy scalar type
for dtype in np.sctypes['int'] + np.sctypes['uint'] + np.sctypes['float']:
    print("{dtype}: Min = {np.iinfo(dtype).min}, Max = {np.iinfo(dtype).max}")


{dtype}: Min = {np.iinfo(dtype).min}, Max = {np.iinfo(dtype).max}
{dtype}: Min = {np.iinfo(dtype).min}, Max = {np.iinfo(dtype).max}
{dtype}: Min = {np.iinfo(dtype).min}, Max = {np.iinfo(dtype).max}
{dtype}: Min = {np.iinfo(dtype).min}, Max = {np.iinfo(dtype).max}
{dtype}: Min = {np.iinfo(dtype).min}, Max = {np.iinfo(dtype).max}
{dtype}: Min = {np.iinfo(dtype).min}, Max = {np.iinfo(dtype).max}
{dtype}: Min = {np.iinfo(dtype).min}, Max = {np.iinfo(dtype).max}
{dtype}: Min = {np.iinfo(dtype).min}, Max = {np.iinfo(dtype).max}
{dtype}: Min = {np.iinfo(dtype).min}, Max = {np.iinfo(dtype).max}
{dtype}: Min = {np.iinfo(dtype).min}, Max = {np.iinfo(dtype).max}
{dtype}: Min = {np.iinfo(dtype).min}, Max = {np.iinfo(dtype).max}


In [56]:
# 49. How to print all the values of an array?
# (Setting print options to display all values)
np.set_printoptions(threshold=np.inf)
large_array = np.arange(100)
print("Large Array:", large_array)

Large Array: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [57]:
# 50. How to find the closest value (to a given scalar) in a vector?
vector_closest_value = np.arange(10)
scalar_value = 7.5
closest_value = vector_closest_value[(np.abs(vector_closest_value - scalar_value)).argmin()]
print("Vector:", vector_closest_value)
print("Closest Value to", scalar_value, ":", closest_value)


Vector: [0 1 2 3 4 5 6 7 8 9]
Closest Value to 7.5 : 7


In [58]:
# 51. Create a structured array representing a position (x,y) and a color (r,g,b)
position_color_array = np.zeros(5, dtype=[('position', [('x', float), ('y', float)]), ('color', [('r', int), ('g', int), ('b', int)])])
print("Structured Array with Position and Color:\n", position_color_array)


Structured Array with Position and Color:
 [((0., 0.), (0, 0, 0)) ((0., 0.), (0, 0, 0)) ((0., 0.), (0, 0, 0))
 ((0., 0.), (0, 0, 0)) ((0., 0.), (0, 0, 0))]


In [59]:
# 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances
coordinates_vector = np.random.random((100, 2))
distances = np.linalg.norm(coordinates_vector[:, np.newaxis] - coordinates_vector, axis=-1)
print("Random Coordinates Vector:\n", coordinates_vector)
print("Distances between Points:\n", distances)

Random Coordinates Vector:
 [[0.98210377 0.8342521 ]
 [0.88515945 0.55357682]
 [0.80309644 0.37456759]
 [0.73209924 0.86828774]
 [0.63131009 0.13150899]
 [0.83040341 0.42222014]
 [0.33338847 0.85461117]
 [0.80218702 0.62515472]
 [0.4374259  0.85176696]
 [0.04389471 0.22712872]
 [0.12038992 0.42728922]
 [0.58301439 0.94795025]
 [0.42844919 0.8050857 ]
 [0.79129669 0.23279121]
 [0.51591431 0.39332957]
 [0.14740501 0.70040173]
 [0.1770903  0.33207142]
 [0.39412386 0.17274702]
 [0.17778174 0.89584863]
 [0.90427389 0.75376028]
 [0.38539451 0.28235963]
 [0.22765147 0.04376282]
 [0.39370261 0.73551132]
 [0.62347702 0.81621815]
 [0.86876313 0.82663555]
 [0.81042532 0.08197006]
 [0.39009705 0.12266984]
 [0.00170743 0.76119046]
 [0.82517186 0.025623  ]
 [0.44645853 0.44255877]
 [0.85827272 0.28198749]
 [0.83980576 0.38706288]
 [0.27424938 0.7728258 ]
 [0.37906792 0.94000741]
 [0.9786993  0.07657871]
 [0.77740078 0.64539718]
 [0.1647551  0.1765903 ]
 [0.4533227  0.37679711]
 [0.40057593 0.9869071

In [60]:
# 53. How to convert a float (32 bits) array into an integer (32 bits) in place?
float_array_32 = np.random.uniform(0, 10, 5).astype(np.float32)
integer_array_32 = float_array_32.view(np.int32)
print("Float (32 bits) Array:\n", float_array_32)
print("Converted Integer (32 bits) Array:\n", integer_array_32)

Float (32 bits) Array:
 [6.051677  3.1312017 6.87209   2.3326635 6.4788537]
Converted Integer (32 bits) Array:
 [1086433111 1078486428 1088153641 1075137116 1087328965]


In [ ]:
# 54. How to read the following file? (★★☆)
# 1, 2, 3, 4, 5
# 6,  ,  , 7, 8
# ,  , 9,10,11

In [ ]:


# 55. What is the equivalent of enumerate for numpy arrays?
array_for_enumerate = np.array(['apple', 'banana', 'cherry'])
for index, value in np.ndenumerate(array_for_enumerate):
    print(f"Index: {index}, Value: {value}")

# 56. Generate a generic 2D Gaussian-like array
x, y = np.meshgrid(np.linspace(-1, 1, 5), np.linspace(-1, 1, 5))
d = np.sqrt(x*x + y*y)
sigma, mu = 1.0, 0.0
gaussian_array = np.exp(-( (d-mu)**2 / ( 2.0 * sigma**2 ) ) )
print("2D Gaussian-like Array:\n", gaussian_array)

# 57. How to randomly place p elements in a 2D array?
p_elements = 3
array_2d_random_p_elements = np.zeros((5, 5))
indices_to_fill = np.random.choice(np.arange(5*5), p_elements, replace=False)
array_2d_random_p_elements.flat[indices_to_fill] = 1
print(f"2D Array with {p_elements} Randomly Placed Elements:\n", array_2d_random_p_elements)

# 58. Subtract the mean of each row of a matrix
matrix_to_subtract_mean = np.random.random((3, 3))
mean_per_row = matrix_to_subtract_mean.mean(axis=1)
matrix_subtracted_mean = matrix_to_subtract_mean - mean_per_row[:, np.newaxis]
print("Original Matrix:\n", matrix_to_subtract_mean)
print("Matrix with Mean of Each Row Subtracted:\n", matrix_subtracted_mean)

# 59. How to sort an array by the nth column?
array_to_sort_by_column = np.array([[1, 3, 2], [5, 1, 6], [2, 7, 4]])
n_column_to_sort_by = 1
sorted_array_by_column = array_to_sort_by_column[array_to_sort_by_column[:, n_column_to_sort_by].argsort()]
print(f"Array Sorted by {n_column_to_sort_by}th Column:\n", sorted_array_by_column)

# 60. How to tell if a given 2D array has null columns?
array_with_null_columns = np.array([[0, 1, 0], [0, 0, 0], [0, 1, 0]])
null_columns = ~array_with_null_columns.any(axis=0)
print("Array with Null Columns:\n", array_with_null_columns)
print("Null Columns:", null_columns)

# 61. Find the nearest value from a given value in an array
array_nearest_value = np.array([1, 2, 3, 4, 5])
given_value = 3.7
nearest_value = array_nearest_value[(np.abs(array_nearest_value - given_value)).argmin()]
print("Array:", array_nearest_value)
print(f"Nearest Value to {given_value}:", nearest_value)

# 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator?
array_1 = np.arange(3).reshape(1, 3)
array_2 = np.arange(3).reshape(3, 1)
iterator_sum = np.nditer([array_1, array_2, None])
for a, b, result in iterator_sum:
    result[...] = a + b
print("Array 1:\n", array_1)
print("Array 2:\n", array_2)
print("Sum using Iterator:\n", iterator_sum.operands[2])

# 63. Create an array class that has a name attribute
class NamedArray(np.ndarray):
    def __new__(cls, array, name=""):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj

# Example usage:
named_array = NamedArray([1, 2, 3], name="ExampleArray")
print("Named Array:", named_array)
print("Name attribute:", named_array.name)

# 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)?
given_vector = np.array([1, 2, 3, 4, 5])
indices_to_add_one = np.array([1, 3, 1, 4])
given_vector += np.bincount(indices_to_add_one, minlength=len(given_vector))
print("Given Vector with 1 added to specified indices:", given_vector)

# 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)?
vector_X = np.array([1, 2, 3, 4, 5])
index_list_I = np.array([1, 3, 1, 4])
accumulated_array_F = np.bincount(index_list_I, weights=vector_X)
print("Vector X:", vector_X)
print("Index List I:", index_list_I)
print("Accumulated Array F:", accumulated_array_F)

# 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors
image_shape = (5, 5, 3)
image_dtype = np.uint8
image_array = np.random.randint(0, 256, size=image_shape, dtype=image_dtype)
unique_colors = len(np.unique(image_array.reshape(-1, 3), axis=0))
print("Number of Unique Colors in Image:", unique_colors)

# 67. Considering a four dimensions array, how to get sum over the last two axis at once?
four_dimensions_array = np.random.random((2, 3, 4, 5))
sum_over_last_two_axes = four_dimensions_array.sum(axis=(-2, -1))
print("Original 4D Array Shape:", four_dimensions_array.shape)
print("Sum over Last Two Axes:", sum_over_last_two_axes)

# 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset indices?
vector_D = np.array([1, 2, 3, 4, 5, 6])
vector_S = np.array([0, 0, 1, 1, 2, 2])
means_of_subsets = np.bincount(vector_S, weights=vector_D) / np.bincount(vector_S)
print("Vector D:", vector_D)
print("Vector S:", vector_S)
print("Means of Subsets:", means_of_subsets)

# 69. How to get the diagonal of a dot product?
matrix_A = np.random.random((3, 3))
matrix_B = np.random.random((3, 3))
dot_product_diagonal = np.diag(np.dot(matrix_A, matrix_B))
print("Matrix A:\n", matrix_A)
print("Matrix B:\n", matrix_B)
print("Diagonal of Dot Product:", dot_product_diagonal)

# 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value?
original_vector = np.array([1, 2, 3, 4, 5])
zeros_interleaved_vector = np.zeros(len(original_vector) + (len(original_vector) - 1) * 3)
zeros_interleaved_vector[::4] = original_vector
print("Original Vector:", original_vector)
print("New Vector with Zeros Interleaved:", zeros_interleaved_vector)
I hope these answers are helpful! If you have any further questions, feel free to ask.

User
answer the remaining questions
ChatGPT
Certainly! Let's continue with the answers to the remaining questions:

python
Copy code
# 71. Consider an array of dimension (5,5,3), how to multiply it by an array with dimensions (5,5)?
array_3d = np.random.random((5, 5, 3))
array_2d = np.random.random((5, 5))
result_multiplication = array_3d * array_2d[:, :, np.newaxis]
print("3D Array Shape:", array_3d.shape)
print("2D Array Shape:", array_2d.shape)
print("Result of Multiplication:", result_multiplication)

# 72. How to swap two rows of an array?
array_to_swap_rows = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
array_to_swap_rows[[0, 1]] = array_to_swap_rows[[1, 0]]
print("Array with Rows Swapped:\n", array_to_swap_rows)

# 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices),
# find the set of unique line segments composing all the triangles
triplets_set = set(tuple(map(tuple, np.random.randint(1, 10, (10, 3)))))
lines_set = set(tuple(sorted([a, b])) for triplet in triplets_set for a, b in zip(triplet, triplet[1:] + triplet[:1]))
print("Set of Unique Line Segments from Triangles:\n", lines_set)

# 74. Given a sorted array C that corresponds to a bincount, how to produce an array A
# such that np.bincount(A) == C?
sorted_bincount_array = np.array([1, 2, 0, 0, 4, 0])
result_array_A = np.repeat(np.arange(len(sorted_bincount_array)), sorted_bincount_array)
print("Sorted Bincount Array:\n", sorted_bincount_array)
print("Result Array A:\n", result_array_A)

# 75. How to compute averages using a sliding window over an array?
array_for_sliding_window = np.arange(10)
window_size = 3
averages_with_sliding_window = np.convolve(array_for_sliding_window, np.ones(window_size)/window_size, mode='valid')
print("Original Array:\n", array_for_sliding_window)
print("Averages with Sliding Window (size = {}):\n".format(window_size), averages_with_sliding_window)

# 76. Consider a one-dimensional array Z, build a two-dimensional array whose
# first row is (Z[0], Z[1], Z[2]) and each subsequent row is shifted by 1
array_for_shifted_rows = np.arange(1, 11)
shifted_rows_array = np.lib.stride_tricks.sliding_window_view(array_for_shifted_rows, (3,))
print("Original Array for Shifted Rows:\n", array_for_shifted_rows)
print("Resultant 2D Array with Shifted Rows:\n", shifted_rows_array)

# 77. How to negate a boolean, or to change the sign of a float inplace?
boolean_array_to_negate = np.array([True, False, True])
negated_boolean_array = np.logical_not(boolean_array_to_negate)
print("Original Boolean Array:\n", boolean_array_to_negate)
print("Negated Boolean Array:\n", negated_boolean_array)

# 78. Consider 2 sets of points P0, P1 describing lines (2d) and a point p,
# how to compute distance from p to each line i (P0[i], P1[i])?
P0 = np.array([[0, 0], [1, 1], [2, 2]])
P1 = np.array([[1, 0], [0, 1], [-1, 0]])
p = np.array([1, 1])
distances_to_lines = np.abs(np.cross(P1 - P0, P0 - p)) / np.linalg.norm(P1 - P0, axis=1)
print("Set of Points P0:\n", P0)
print("Set of Points P1:\n", P1)
print("Point P:\n", p)
print("Distances from P to Lines (P0[i], P1[i]):\n", distances_to_lines)

# 79. Consider 2 sets of points P0, P1 describing lines (2d) and a set of points P,
# how to compute distance from each point j (P[j]) to each line i (P0[i], P1[i])?
P = np.array([[0, 1], [1, 2], [2, 3], [3, 4]])
distances_from_points_to_lines = np.array([np.abs(np.cross(P1 - P0, P0 - p)) / np.linalg.norm(P1 - P0, axis=1)
                                           for p in P])
print("Set of Points P:\n", P)
print("Distances from Points to Lines (P0[i], P1[i]):\n", distances_from_points_to_lines)

# 80. Consider an arbitrary array, write a function that extracts a subpart with a fixed shape
# and centered on a given element (pad with a fill value when necessary)
def extract_subpart(array, shape, center):
    indices = np.arange(center - shape // 2, center + shape // 2)
    indices = np.clip(indices, 0, len(array))
    subpart = np.full(shape, fill_value=array[0, 0])
    subpart[indices] = array[indices]
    return subpart

array_for_subpart_extraction = np.random.randint(1, 10, (7, 7))
shape_of_subpart = (3, 3)
center_of_subpart = (3, 3)
subpart_result = extract_subpart(array_for_subpart_extraction, shape_of_subpart, center_of_subpart)
print("Original Array for Subpart Extraction:\n", array_for_subpart_extraction)
print("Resultant Subpart with Shape {} Centered at {}:\n".format(shape_of_subpart, center_of_subpart), subpart_result)

# 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array
# R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]?
original_array_Z = np.arange(1, 15)
array_R = np.lib.stride_tricks.sliding_window_view(original_array_Z, (4,))
print("Original Array Z:\n", original_array_Z)
print("Resultant Array R:\n", array_R)

# 82. Compute a matrix rank
matrix_for_rank = np.random.random((4, 4))
rank_of_matrix = np.linalg.matrix_rank(matrix_for_rank)
print("Matrix for Rank Computation:\n", matrix_for_rank)
print("Rank of Matrix:", rank_of_matrix)

# 83. How to find the most frequent value in an array?
array_for_most_frequent_value = np.array([1, 2, 3, 2, 2, 1, 3, 4, 2, 4, 2, 5])
most_frequent_value = np.bincount(array_for_most_frequent_value).argmax()
print("Array for Most Frequent Value:\n", array_for_most_frequent_value)
print("Most Frequent Value:", most_frequent_value)

# 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix
random_10x10_matrix = np.random.random((10, 10))
contiguous_blocks_3x3 = np.lib.stride_tricks.sliding_window_view(random_10x10_matrix, (3, 3))
print("Random 10x10 Matrix:\n", random_10x10_matrix)
print("Contiguous 3x3 Blocks:\n", contiguous_blocks_3x3)

# 85. Create a 2D array subclass such that Z[i,j] == Z[j,i]
class SymmetricArray(np.ndarray):
    def __setitem__(self, index, value):
        super().__setitem__((index[1], index[0]), value)

symmetric_array = SymmetricArray((3, 3), dtype=int)
symmetric_array[0, 1] = 1
symmetric_array[1, 2] = 2
symmetric_array[2, 0] = 3
print("Symmetric Array (Z[i,j] == Z[j,i]):\n", symmetric_array)

# 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1).
# How to compute the sum of the p matrix products at once? (result has shape (n,1))
p_matrices = [np.random.random((3, 3)) for _ in range(5)]
p_vectors = [np.random.random((3, 1)) for _ in range(5)]
sum_of_matrix_products = np.sum([np.dot(matrix, vector) for matrix, vector in zip(p_matrices, p_vectors)], axis=0)
print("Set of Matrices (p) with Shape (3, 3):\n", p_matrices)
print("Set of Vectors (p) with Shape (3, 1):\n", p_vectors)
print("Sum of Matrix Products (Result Shape: (3, 1)):\n", sum_of_matrix_products)

# 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)?
array_16x16 = np.random.random((16, 16))
block_sum_4x4 = np.lib.stride_tricks.sliding_window_view(array_16x16, (4, 4)).sum(axis=(2, 3))
print("Original 16x16 Array:\n", array_16x16)
print("Block-Sum with Block Size 4x4:\n", block_sum_4x4)

# 88. How to implement the Game of Life using numpy arrays?
def game_of_life(board, generations):
    for _ in range(generations):
        neighbors_count = sum(np.roll(np.roll(board, i, 0), j, 1)
                             for i in (-1, 0, 1) for j in (-1, 0, 1) if (i != 0 or j != 0))
        board = (neighbors_count == 3) | (board & (neighbors_count == 2))
    return board

initial_board = np.random.choice([0, 1], size=(10, 10))
generations_to_simulate = 5
final_board = game_of_life(initial_board, generations_to_simulate)
print("Initial Game of Life Board:\n", initial_board)
print("Final Game of Life Board after {} Generations:\n".format(generations_to_simulate), final_board)

# 89. How to get the n largest values of an array?
array_for_n_largest_values = np.random.random(10)
n_largest_values_indices = np.argpartition(array_for_n_largest_values, -3)[-3:]
n_largest_values = array_for_n_largest_values[n_largest_values_indices]
print("Array for N Largest Values:\n", array_for_n_largest_values)
print("Indices of N Largest Values:", n_largest_values_indices)
print("N Largest Values:", n_largest_values)

# 90. Given an arbitrary number of vectors, build the cartesian product
# (every combination of every item)
vectors_for_cartesian_product = [np.array([1, 2]), np.array([3, 4]), np.array([5, 6])]
cartesian_product = np.array(np.meshgrid(*vectors_for_cartesian_product)).T.reshape(-1, len(vectors_for_cartesian_product))
print("Vectors for Cartesian Product:\n", vectors_for_cartesian_product)
print("Cartesian Product:\n", cartesian_product)

# 91. How to create a record array from a regular array?
regular_array_for_record_array = np.array([(1, 'John', 25), (2, 'Jane', 30), (3, 'Doe', 22)],
                                          dtype=[('ID', int), ('Name', 'U10'), ('Age', int)])
record_array = np.rec.array(regular_array_for_record_array)
print("Regular Array for Record Array:\n", regular_array_for_record_array)
print("Record Array:\n", record_array)

# 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods
large_vector_Z = np.random.random(1000000)
method1_result = np.power(Z, 3)
method2_result = Z ** 3
method3_result = np.einsum('i,i,i->i', Z, Z, Z)
print("Large Vector Z (First 5 Elements):\n", large_vector_Z[:5])
print("Result of Z to the Power of 3 (Method 1):\n", method1_result[:5])
print("Result of Z to the Power of 3 (Method 2):\n", method2_result[:5])
print("Result of Z to the Power of 3 (Method 3):\n", method3_result[:5])

# 93. Consider two arrays A and B of shape (8,3) and (2,2).
# How to find rows of A that contain elements of each row of B regardless of the order of the elements in B?
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12],
              [13, 14, 15], [16, 17, 18], [19, 20, 21], [22, 23, 24]])
B = np.array([[2, 1], [8, 7]])
rows_containing_elements_of_B = np.all(np.isin(A, B), axis=1)
print("Array A (Shape: {}):\n".format(A.shape), A)
print("Array B (Shape: {}):\n".format(B.shape), B)
print("Rows of A Containing Elements of B:\n", rows_containing_elements_of_B)

# 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3])
matrix_for_unequal_rows = np.array([[1, 1, 1], [2, 2, 3], [4, 5, 6], [7, 7, 7],
                                   [8, 8, 9], [10, 11, 12], [13, 13, 13], [14, 15, 16], [17, 18, 19], [20, 21, 21]])
unequal_rows = np.any(np.diff(matrix_for_unequal_rows, axis=1) != 0, axis=1)
print("Original Matrix for Unequal Rows (10x3):\n", matrix_for_unequal_rows)
print("Rows with Unequal Values:\n", unequal_rows)

# 95. Convert a vector of ints into a matrix binary representation
vector_for_binary_representation = np.array([1, 2, 3, 4], dtype=np.uint8)
binary_representation_matrix = np.unpackbits(vector_for_binary_representation[:, np.newaxis], axis=1)
print("Vector for Binary Representation:\n", vector_for_binary_representation)
print("Matrix Binary Representation:\n", binary_representation_matrix)

# 96. Given a two-dimensional array, how to extract unique rows?
two_dimensional_array_for_unique_rows = np.array([[1, 2, 3], [4, 5, 6], [1, 2, 3], [7, 8, 9], [4, 5, 6]])
unique_rows = np.unique(two_dimensional_array_for_unique_rows, axis=0)
print("Original 2D Array for Unique Rows:\n", two_dimensional_array_for_unique_rows)
print("Unique Rows:\n", unique_rows)

# 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function
A_for_einsum = np.array([1, 2, 3])
B_for_einsum = np.array([4, 5, 6])
inner_product = np.einsum('i,i', A_for_einsum, B_for_einsum)
outer_product = np.einsum('i,j->ij', A_for_einsum, B_for_einsum)
sum_result = np.einsum('i', A_for_einsum)
elementwise_product = np.einsum('i,i->i', A_for_einsum, B_for_einsum)
print("Vector A for Einsum:\n", A_for_einsum)
print("Vector B for Einsum:\n", B_for_einsum)
print("Einsum Equivalent of Inner Product:\n", inner_product)
print("Einsum Equivalent of Outer Product:\n", outer_product)
print("Einsum Equivalent of Sum:\n", sum_result)
print("Einsum Equivalent of Elementwise Product:\n", elementwise_product)

# 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples?
X_for_path_sampling = np.array([1, 2, 3, 4, 5])
Y_for_path_sampling = np.array([10, 15, 7, 12, 8])
equidistant_samples = np.linspace(0, 1, 100)
sampled_path = np.column_stack([np.interp(equidistant_samples, np.linspace(0, 1, len(X_for_path_sampling)), X_for_path_sampling),
                               np.interp(equidistant_samples, np.linspace(0, 1, len(Y_for_path_sampling)), Y_for_path_sampling)])
print("Vector X for Path Sampling:\n", X_for_path_sampling)
print("Vector Y for Path Sampling:\n", Y_for_path_sampling)
print("Equidistant Samples:\n", equidistant_samples)
print("Sampled Path:\n", sampled_path)

# 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as
# draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers
# and which sum to n.
n_for_multinomial = 5
array_X_for_multinomial = np.array([[1, 2, 2], [2, 1, 2], [0, 5, 0], [3, 1, 1], [1, 1, 3], [0, 2, 3]])
valid_rows_for_multinomial = (array_X_for_multinomial.sum(axis=1) == n_for_multinomial) & np.all(array_X_for_multinomial.astype(int) == array_X_for_multinomial, axis=1)
selected_rows_for_multinomial = array_X_for_multinomial[valid_rows_for_multinomial]
print("Integer n for Multinomial Distribution:", n_for_multinomial)
print("2D Array X for Multinomial Distribution:\n", array_X_for_multinomial)
print("Rows that can be interpreted as draws from Multinomial Distribution:\n", selected_rows_for_multinomial)

# 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X
array_X_for_bootstrapping = np.random.normal(0, 1, 1000)
bootstrap_samples = np.random.choice(array_X_for_bootstrapping, (10000, len(array_X_for_bootstrapping)), replace=True)
confidence_interval_lower, confidence_interval_upper = np.percentile(bootstrap_samples.mean(axis=1), [2.5, 97.5])
print("1D Array X for Bootstrapping (First 5 Elements):\n", array_X_for_bootstrapping[:5])
print("Bootstrapped 95% Confidence Interval for the Mean:\n", (confidence_interval_lower, confidence_interval_upper))
This concludes the